function Hero(obj){
	this.name = obj.name;
	this.maxhealth = obj.health;
	this.health = this.maxhealth;
	this.health = obj.maxhealth;
	this.class = obj.class;
	this.heropower = obj.heropower;
	this.heropowerflag = true;
	this.type = ["Hero"];
	this.reflash = [];
	this.effect = [];
	if (obj.type != undefined)
		this.type.concat(obj.type);
	this.TakeDamageTrigger = [];
	this.DealingDamageTrigger = [];
	this.heropowerflag = true;
	this.attack = 0;
	this.attacktime = 1;
	this.exhaustion = true;
	this.armor = 0;
	this.heropowercost = 2;
	this.heropower = obj.heropower;
	this.HeropowerCheck = (obj.HeropowerCheck != undefined) ? (obj.HeropowerCheck) : (function(){return true;});
	this.StartTurnTrigger = obj.StartTurnTrigger==undefined ? [] : obj.StartTurnTrigger;
	this.YourStartTurnTrigger = obj.YourStartTurnTrigger==undefined ? [] : obj.YourStartTurnTrigger;
	this.OpponentStartTurnTrigger = obj.OpponentStartTurnTrigger==undefined ? [] : obj.OpponentStartTurnTrigger;
	this.EndTurnTrigger = obj.EndTurnTrigger==undefined ? [] : obj.EndTurnTrigger;
	this.YourEndTurnTrigger = obj.YourEndTurnTrigger==undefined ? [] : obj.YourEndTurnTrigger;
	this.OpponentEndTurnTrigger = obj.OpponentEndTurnTrigger==undefined ? [] : obj.OpponentEndTurnTrigger;
	this.RevealSecretTrigger = obj.RevealSecretTrigger==undefined ? [] : obj.RevealSecretTrigger;
	this.YourRevealSecretTrigger = obj.YourRevealSecretTrigger==undefined ? [] : obj.YourRevealSecretTrigger;
	this.OpponentRevealSecretTrigger = obj.OpponentRevealSecretTrigger==undefined ? [] : obj.OpponentRevealSecretTrigger;
	this.UseSpellTrigger = obj.UseSpellTrigger==undefined ? [] : obj.UseSpellTrigger;
	this.YourUseSpellTrigger = obj.YourUseSpellTrigger==undefined ? [] : obj.YourUseSpellTrigger;
	this.OpponentUseSpellTrigger = obj.OpponentUseSpellTrigger==undefined ? [] : obj.OpponentUseSpellTrigger;
	this.YourSpellTargetTrigger = obj.YourSpellTargetTrigger==undefined ? [] : obj.YourSpellTargetTrigger;
	this.AfterSpellTrigger = obj.AfterSpellTrigger==undefined ? [] : obj.AfterSpellTrigger;
	this.YourAfterSpellTrigger = obj.YourAfterSpellTrigger==undefined ? [] : obj.YourAfterSpellTrigger;
	this.OpponentAfterSpellTrigger = obj.OpponentAfterSpellTrigger==undefined ? [] : obj.OpponentAfterSpellTrigger;
	this.PlayMinionsTrigger = obj.PlayMinionsTrigger==undefined ? [] : obj.PlayMinionsTrigger;
	this.YourPlayMinionsTrigger = obj.YourPlayMinionsTrigger==undefined ? [] : obj.YourPlayMinionsTrigger;
	this.OpponentPlayMinionsTrigger = obj.OpponentPlayMinionsTrigger==undefined ? [] : obj.OpponentPlayMinionsTrigger;
	this.SummonTrigger = obj.SummonTrigger==undefined ? [] : obj.SummonTrigger;
	this.YourSummonTrigger = obj.YourSummonTrigger==undefined ? [] : obj.YourSummonTrigger;
	this.OpponentSummonTrigger = obj.OpponentSummonTrigger==undefined ? [] : obj.OpponentSummonTrigger;
	this.AfterPlayMinionsTrigger = obj.AfterPlayMinionsTrigger==undefined ? [] : obj.AfterPlayMinionsTrigger;
	this.YourAfterPlayMinionsTrigger = obj.YourAfterPlayMinionsTrigger==undefined ? [] : obj.YourAfterPlayMinionsTrigger;
	this.OpponentAfterPlayMinionsTrigger = obj.OpponentAfterPlayMinionsTrigger==undefined ? [] : obj.OpponentAfterPlayMinionsTrigger;
	this.AfterSummonTrigger = obj.AfterSummonTrigger==undefined ? [] : obj.AfterSummonTrigger;
	this.YourAfterSummonTrigger = obj.YourAfterSummonTrigger==undefined ? [] : obj.YourAfterSummonTrigger;
	this.OpponentAfterSummonTrigger = obj.OpponentAfterSummonTrigger==undefined ? [] : obj.OpponentAfterSummonTrigger;
	this.BeforAttackTrigger = obj.BeforAttackTrigger==undefined ? [] : obj.BeforAttackTrigger;
	this.AttackTrigger = obj.AttackTrigger==undefined ? [] : obj.AttackTrigger;
	this.AfterAttackTrigger = obj.AfterAttackTrigger==undefined ? [] : obj.AfterAttackTrigger;
	this.OngoingEffect = obj.OngoingEffect==undefined ? [] : obj.OngoingEffect;
}